#!/bin/bash
cat "introduction.txt"
cat "start fights.txt"
cat "never wrestle the bull.txt"
cat "dont be the bull.txt"
cat "lie.txt"
cat "run away.txt"
cat "what if it isnt about animal rights.txt"
cat "killing the bull is optional.txt"
cat "whats it like to see a real bullfight.txt"
cat "how is this different from gambling.txt"
cat "lots of goes.txt"
cat "when you get gored.txt"
cat "can you fight yourself is that wise.txt"
cat "when youre not fighting dont fight.txt"
cat "fighting bulls doesnt mean being a bully.txt"
